/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Colaborador;
import backend.ColaboradorPago;
import backend.ColaboradorVoluntario;
import backend.Festival;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author Miguel
 */
public class ColaboradorForm extends javax.swing.JFrame {

    private Menu anterior;
    private List<Festival> festivais;
    private Colaborador colaborador;
    private Festival festival;
    
     public ColaboradorForm() {
        
        initComponents();
     }
    /**
     * Creates new form Colaborador
     */
    public ColaboradorForm(Menu anterior) {
        initComponents();
        this.anterior = anterior;
        
        
    }
    
    public ColaboradorForm(Menu menu, List<Festival> fest) {
        initComponents();
        this.anterior = menu;
        this.festivais = fest;
        
        ComboBoxModel comboModel = new DefaultComboBoxModel(fest.toArray());
        
        colaboradorFestivalCombo.setModel(comboModel);
    }
    
    public ColaboradorForm(Menu menu, List<Festival> fest, Colaborador colaborador, Festival festival) {
        initComponents();
        this.anterior = menu;
        this.festivais = fest;
        this.colaborador = colaborador;
        this.festival = festival;
        
        ComboBoxModel comboModel = new DefaultComboBoxModel(fest.toArray());
        
        colaboradorFestivalCombo.setModel(comboModel);
        
        colaboradorFestivalCombo.setEnabled(false);
        tipoColaboradorInput.setEnabled(false);
        
        preencheColaborador();
    }
    
    public void preencheColaborador() {
        nomeColaboradorInput.setText(colaborador.getNome());
        telefoneColaboradorInput.setText("" + colaborador.getTelefone());
        moradaColaboradorInput.setText(colaborador.getMorada());
        funcaoColaboradorInput.setText(colaborador.getFuncao());
        
        colaboradorFestivalCombo.setSelectedItem(festival);
        colaboradorFestivalCombo.setEditable(false);
        
        if(colaborador instanceof ColaboradorPago) {
            tipoColaboradorInput.setSelectedIndex(0);
            nifColaboradorInput.setText("" + ((ColaboradorPago) colaborador).getNif());
            pagamentoColaboradorInput.setText("" + ((ColaboradorPago) colaborador).getPagamento());
        }
        else {
            tipoColaboradorInput.setSelectedIndex(1);
        }
        
    }
    
    public void voltar(){
        JFrame janela;
        
        if (this.anterior != null) {
            janela = anterior;
        }
        else {
            janela = new Menu();
            janela.setLocationRelativeTo(null);
        }
        
        this.setVisible(false);
        janela.setVisible(true);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeColaboradorInput = new javax.swing.JTextField();
        telefoneColaboradorInput = new javax.swing.JTextField();
        moradaColaboradorInput = new javax.swing.JTextField();
        funcaoColaboradorInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipoColaboradorInput = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nifColaboradorInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pagamentoColaboradorInput = new javax.swing.JTextField();
        colaboradorFestivalLabel = new javax.swing.JLabel();
        colaboradorFestivalCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Colaborador");

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Morada:");

        jLabel5.setText("Função:");

        nomeColaboradorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeColaboradorInputActionPerformed(evt);
            }
        });

        telefoneColaboradorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneColaboradorInputActionPerformed(evt);
            }
        });

        moradaColaboradorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moradaColaboradorInputActionPerformed(evt);
            }
        });

        jLabel6.setText("Todos os campos devem ser preenchidos");

        jLabel7.setText("Tipo:");

        tipoColaboradorInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colaborador Pago", "Colaborador Voluntário" }));
        tipoColaboradorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoColaboradorInputActionPerformed(evt);
            }
        });

        jButton2.setText("Gravar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("NIF:");

        nifColaboradorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nifColaboradorInputActionPerformed(evt);
            }
        });

        jLabel9.setText("Pagamento:");

        colaboradorFestivalLabel.setText("Festival");

        colaboradorFestivalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        colaboradorFestivalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaboradorFestivalComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nomeColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(moradaColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(telefoneColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(funcaoColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pagamentoColaboradorInput)
                                        .addComponent(nifColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(colaboradorFestivalLabel)
                                .addGap(18, 18, 18)
                                .addComponent(colaboradorFestivalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 358, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colaboradorFestivalLabel)
                    .addComponent(colaboradorFestivalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nomeColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(telefoneColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moradaColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcaoColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nifColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pagamentoColaboradorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeColaboradorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeColaboradorInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeColaboradorInputActionPerformed

    private void telefoneColaboradorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneColaboradorInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneColaboradorInputActionPerformed

    private void moradaColaboradorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moradaColaboradorInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moradaColaboradorInputActionPerformed

    private void tipoColaboradorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoColaboradorInputActionPerformed
        String escolha = (String) tipoColaboradorInput.getSelectedItem();
        if(escolha.equals("Colaborador Pago")){
            nifColaboradorInput.setVisible(true);
            pagamentoColaboradorInput.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
        }
        else {
            nifColaboradorInput.setVisible(false);
            pagamentoColaboradorInput.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
        }
  
    }//GEN-LAST:event_tipoColaboradorInputActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: 
        JFrame janela;
        
        if (this.anterior != null) {
            janela = anterior;
        }
        else {
            janela = new Menu();
            janela.setLocationRelativeTo(null);
        }
        
        this.setVisible(false);
        janela.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nifColaboradorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nifColaboradorInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nifColaboradorInputActionPerformed

    private void colaboradorFestivalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaboradorFestivalComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colaboradorFestivalComboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Colaborador colaborador;
        
        //estamos a atualizar ou criar?
        if (this.colaborador != null) {
            colaborador = this.colaborador;
        }
        else {
            if (tipoColaboradorInput.getSelectedIndex() == 0) {
                colaborador = new ColaboradorPago();
            }
            else {
                colaborador = new ColaboradorVoluntario();
            }
        }
        
        int telefoneColaborador = 0;
        
        try {
            telefoneColaborador = Integer.parseInt(telefoneColaboradorInput.getText());
        }
        catch (NumberFormatException ne) {
            System.out.println("Não foi possivel ler o numero");
        }
        
        colaborador.setNome(nomeColaboradorInput.getText());
        colaborador.setFuncao(funcaoColaboradorInput.getText());
        colaborador.setMorada(moradaColaboradorInput.getText());
        colaborador.setTelefone(telefoneColaborador);
        
        if (tipoColaboradorInput.getSelectedIndex() == 0) {
            int nifColaborador = 0;
            double pagamentoColaborador = 0;
        
            try {
                nifColaborador = Integer.parseInt(nifColaboradorInput.getText());
                pagamentoColaborador = Double.parseDouble(pagamentoColaboradorInput.getText());
            }
            catch (NumberFormatException ne) {
                System.out.println("Não foi possivel ler o numero");
            }
        
            ((ColaboradorPago)colaborador).setNif(nifColaborador);
            ((ColaboradorPago)colaborador).setPagamento(pagamentoColaborador);
        }
        
        //Se é atualização não adiciona ao arraylist porque ja la está
        if (this.colaborador == null) {
            
            Festival f = (Festival) colaboradorFestivalCombo.getSelectedItem();
            f.getColaboradores().add(colaborador);
        }
        
        anterior.refreshListaColaboradores();
        
        voltar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        anterior.terminar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColaboradorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColaboradorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColaboradorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColaboradorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColaboradorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> colaboradorFestivalCombo;
    private javax.swing.JLabel colaboradorFestivalLabel;
    private javax.swing.JTextField funcaoColaboradorInput;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField moradaColaboradorInput;
    private javax.swing.JTextField nifColaboradorInput;
    private javax.swing.JTextField nomeColaboradorInput;
    private javax.swing.JTextField pagamentoColaboradorInput;
    private javax.swing.JTextField telefoneColaboradorInput;
    private javax.swing.JComboBox<String> tipoColaboradorInput;
    // End of variables declaration//GEN-END:variables
}
