/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Festival;
import backend.Patrocinio;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author João
 */
public class NovoPatrocinador extends JFrame {

    
    private Menu anterior;
    private List<Festival> festivais;
    private Patrocinio patrocinio;
    private Festival festival;
    /**
     * Creates new form NewJFrame
     */
    public NovoPatrocinador() {
        initComponents();
        contribuicaoPatrocinioInput.setModel(new SpinnerNumberModel(1,0,100,1));
    }
    
    public NovoPatrocinador(Menu anterior){
        
        initComponents();
        
        this.anterior = anterior;
        contribuicaoPatrocinioInput.setModel(new SpinnerNumberModel(1,0,100,1));
    }
    
    public NovoPatrocinador(Menu menu, List<Festival> fest) {
        initComponents();
        this.anterior = menu;
        this.festivais = fest;
        
        ComboBoxModel comboModel = new DefaultComboBoxModel(fest.toArray());
        
        patrocinioFestivalCombo.setModel(comboModel);
    }
    
    public NovoPatrocinador(Menu menu, List<Festival> fest, Patrocinio patrocinio, Festival festival) {
        initComponents();
        this.anterior = menu;
        this.festivais = fest;
        this.patrocinio = patrocinio;
        this.festival = festival;
        
        ComboBoxModel comboModel = new DefaultComboBoxModel(fest.toArray());
        
        patrocinioFestivalCombo.setModel(comboModel);
        
        patrocinioFestivalCombo.setEnabled(false);
        
        preenchePatrocinio();
    }
    
    public void preenchePatrocinio() {
        nomePatrocinioInput.setText(patrocinio.getPatrocinador());
        contribuicaoPatrocinioInput.setValue(patrocinio.getContribuicao());
        
        patrocinioFestivalCombo.setSelectedItem(festival);
        patrocinioFestivalCombo.setEditable(false);        
    }
    
    public void setAnterior(Menu anterior){
        this.anterior = anterior;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomePatrocinioInput = new javax.swing.JTextField();
        patrocinioFestivalCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        guardarPatrocinio = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        contribuicaoPatrocinioInput = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Contribuiçao:");

        jLabel3.setText("Registar Novo Patrocinador");

        patrocinioFestivalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        patrocinioFestivalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patrocinioFestivalComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Festival:");

        guardarPatrocinio.setText("Gravar");
        guardarPatrocinio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPatrocinioActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        contribuicaoPatrocinioInput.setEditor(new javax.swing.JSpinner.NumberEditor(contribuicaoPatrocinioInput, ""));
        contribuicaoPatrocinioInput.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                contribuicaoPatrocinioInputStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(contribuicaoPatrocinioInput, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(patrocinioFestivalCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 152, Short.MAX_VALUE)
                                .addComponent(nomePatrocinioInput, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(guardarPatrocinio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomePatrocinioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contribuicaoPatrocinioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patrocinioFestivalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarPatrocinio)
                    .addComponent(jButton2))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patrocinioFestivalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patrocinioFestivalComboActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_patrocinioFestivalComboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       voltar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void voltar() {
        JFrame janela;
        
        if (this.anterior != null){
            janela = anterior;
        }
        else{
            janela = new Menu();
            janela.setLocationRelativeTo(null);
        }
        
        this.setVisible(false);
        janela.setVisible(true);
    }
    
    private void contribuicaoPatrocinioInputStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_contribuicaoPatrocinioInputStateChanged

    }//GEN-LAST:event_contribuicaoPatrocinioInputStateChanged

    private void guardarPatrocinioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPatrocinioActionPerformed
        Patrocinio patrocinio;
        
        //estamos a atualizar ou criar?
        if (this.patrocinio != null) {
            patrocinio = this.patrocinio;
        }
        else {
            patrocinio = new Patrocinio();
        }
        
        double contrib = 0;
        
        try {
            Object contr = contribuicaoPatrocinioInput.getValue();
            
            if (contr instanceof Integer) {
                contrib = ((Integer) contr).doubleValue();
            }
            else {
                contrib = (Double) contribuicaoPatrocinioInput.getValue();
            }
        }
        catch (NumberFormatException ne) {
            System.out.println("Não foi possivel ler o numero");
        }
        
        patrocinio.setPatrocinador(nomePatrocinioInput.getText());
        patrocinio.setContribuicao(contrib);
        
        //Se é atualização não adiciona ao arraylist porque ja la está
        if (this.patrocinio == null) {
            
            Festival f = (Festival) patrocinioFestivalCombo.getSelectedItem();
            f.getPatrocinio().add(patrocinio);
        }
        
        anterior.refreshListaPatrocinadores();
                
        voltar();        
    }//GEN-LAST:event_guardarPatrocinioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        anterior.terminar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoPatrocinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoPatrocinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoPatrocinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoPatrocinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoPatrocinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner contribuicaoPatrocinioInput;
    private javax.swing.JButton guardarPatrocinio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomePatrocinioInput;
    private javax.swing.JComboBox<String> patrocinioFestivalCombo;
    // End of variables declaration//GEN-END:variables
}
